const bcrypt = require('bcryptjs');
const prisma = require('./lib/prisma');

// First year CSE students data - Roll numbers start with 25BD1A05
const firstYearStudents = [
  { rollNo: "25BD1A0501", name: "ADITYA KONDURU", section: "A" },
  { rollNo: "25BD1A0502", name: "ADVAITH REDDY VEMULA", section: "A" },
  { rollNo: "25BD1A0503", name: "AGURLA SIDDARTH", section: "A" },
  { rollNo: "25BD1A0504", name: "ANUGA CHARAN TEJ", section: "A" },
  { rollNo: "25BD1A0505", name: "ANUGUTHALA SHIVA", section: "A" },
  { rollNo: "25BD1A0506", name: "AVULA SIDDHARTH", section: "A" },
  { rollNo: "25BD1A0507", name: "BADDAM SRUJAN REDDY", section: "A" },
  { rollNo: "25BD1A0508", name: "BAIREDDY YASHA SRI", section: "A" },
  { rollNo: "25BD1A0509", name: "BANDARI ANIRUDH YADAV", section: "A" },
  { rollNo: "25BD1A050A", name: "BARIGADA JAGRUTHI", section: "A" },
  { rollNo: "25BD1A050B", name: "BODHANAPU MANOGNA", section: "A" },
  { rollNo: "25BD1A050C", name: "BOKKA VIKAS", section: "A" },
  { rollNo: "25BD1A050D", name: "BOLAKONDA TEJASREE", section: "A" },
  { rollNo: "25BD1A050E", name: "BOOTHKUR SAIVARSHITH REDDY", section: "A" },
  { rollNo: "25BD1A050F", name: "CHANDANA BASIREDDY", section: "A" },
  { rollNo: "25BD1A050G", name: "CHANDIKA SREESH NARAYAN", section: "A" },
  { rollNo: "25BD1A050H", name: "DEVANABOYINA CHARMITH", section: "A" },
  { rollNo: "25BD1A050J", name: "ELLANDHULA LAXMI SANTHOSHI", section: "A" },
  { rollNo: "25BD1A050K", name: "EMMADI SAI SAHASRA", section: "A" },
  { rollNo: "25BD1A050L", name: "GANDEPALLY SRIRAM DATTA", section: "A" },
  { rollNo: "25BD1A050M", name: "GOSULA AKHILA", section: "A" },
  { rollNo: "25BD1A050N", name: "GUDDAM MANOJ", section: "A" },
  { rollNo: "25BD1A050P", name: "GUDURU SURYATEJA", section: "A" },
  { rollNo: "25BD1A050Q", name: "GUNREDDY MEGHANA", section: "A" },
  { rollNo: "25BD1A050R", name: "JITENDRIYA SHARMA", section: "A" },
  { rollNo: "25BD1A050T", name: "KANDHIKONDA ABHIRAM", section: "A" },
  { rollNo: "25BD1A050U", name: "KANUMURI SRAVAN", section: "A" },
  { rollNo: "25BD1A050V", name: "KARRA SAI SRINIDHI", section: "A" },
  { rollNo: "25BD1A050W", name: "KATHI SAHASRA", section: "A" },
  { rollNo: "25BD1A050X", name: "KATTAGANI NIKHIL", section: "A" },
  { rollNo: "25BD1A050Y", name: "KOTA SAI AKSHAYA", section: "A" },
  { rollNo: "25BD1A050Z", name: "MALEGOUNI LAKSHMI SAI RAAGGHAV", section: "A" },
  { rollNo: "25BD1A0511", name: "MANCHIKANTI YASHWANTH", section: "A" },
  { rollNo: "25BD1A0512", name: "MANDA SHRADDHA TANVITA", section: "A" },
  { rollNo: "25BD1A0513", name: "MOHAMMED AHSAN AHMED", section: "A" },
  { rollNo: "25BD1A0514", name: "MOOSAPETA ANIKETH YADAV", section: "A" },
  { rollNo: "25BD1A0515", name: "MUDIGONDA AKSHAY", section: "A" },
  { rollNo: "25BD1A0516", name: "MUTHIREDDY TANMAYEE", section: "A" },
  { rollNo: "25BD1A0517", name: "N THANMAYE", section: "A" },
  { rollNo: "25BD1A0518", name: "NAGAVARAM NISHANTH", section: "A" },
  { rollNo: "25BD1A0519", name: "NALLAN CHAKRAVERTHULA SUDHAMSH VARUN", section: "A" },
  { rollNo: "25BD1A051A", name: "NIREK TIWARI", section: "A" },
  { rollNo: "25BD1A051B", name: "ORUGANTI MANEESHWAR PRASAD", section: "A" },
  { rollNo: "25BD1A051C", name: "P SIDDHARTHA", section: "A" },
  { rollNo: "25BD1A051D", name: "PABBA SRICHARAN", section: "A" },
  { rollNo: "25BD1A051E", name: "PALA HARSHITH", section: "A" },
  { rollNo: "25BD1A051F", name: "PALLAPOTHU SAI PRERIT GUPTA", section: "A" },
  { rollNo: "25BD1A051G", name: "PARIPELLY HARSHITH", section: "A" },
  { rollNo: "25BD1A051H", name: "POLICE MANOJ PATIL", section: "A" },
  { rollNo: "25BD1A051J", name: "RAJOLI SHIVANSHU", section: "A" },
  { rollNo: "25BD1A051K", name: "RAMAVATH SHIVA PRAKASH", section: "A" },
  { rollNo: "25BD1A051L", name: "RATHLAVATH DILIP KUMAR", section: "A" },
  { rollNo: "25BD1A051M", name: "ROUTHU KAVITHA", section: "A" },
  { rollNo: "25BD1A051N", name: "SAMALA MOUNIKA", section: "A" },
  { rollNo: "25BD1A051P", name: "SRUTHI BOORA", section: "A" },
  { rollNo: "25BD1A051Q", name: "SUTRAVE SAUMYA", section: "A" },
  { rollNo: "25BD1A051R", name: "TANGALLAPALLY ANJANI DEVI", section: "A" },
  { rollNo: "25BD1A051T", name: "THOTAKURI VINITH", section: "A" },
  { rollNo: "25BD1A051U", name: "THUMMAGANTI MOKSHITH", section: "A" },
  { rollNo: "25BD1A051V", name: "VADDEKUNTA PARASHURAM", section: "A" },
  { rollNo: "25BD1A051W", name: "VADDEPALLY HARIPRASAD", section: "A" },
  { rollNo: "25BD1A051X", name: "VANNADA LAXMI CHANDHANA", section: "A" },
  { rollNo: "25BD1A051Y", name: "VASIREDDY NITHISH MADHAV", section: "A" },
  { rollNo: "25BD1A051Z", name: "VOLUKULA KOUSHIK KALYAN", section: "A" },
  { rollNo: "25BD1A0521", name: "A SAI PRAPUL SHASHANK", section: "B" },
  { rollNo: "25BD1A0522", name: "AVULA JYOSHNA", section: "B" },
  { rollNo: "25BD1A0523", name: "BAKKA RAVI CHANDRA", section: "B" },
  { rollNo: "25BD1A0524", name: "BATTU ADITH REDDY", section: "B" },
  { rollNo: "25BD1A0525", name: "BIJJALA SAI MANISH", section: "B" },
  { rollNo: "25BD1A0526", name: "BODDU BHARATH KUMAR", section: "B" },
  { rollNo: "25BD1A0527", name: "BODDU MAANVITHA REDDY", section: "B" },
  { rollNo: "25BD1A0528", name: "BOPPU VIVEK VARMA", section: "B" },
  { rollNo: "25BD1A0529", name: "BURRA VARSHITH", section: "B" },
  { rollNo: "25BD1A052A", name: "BURSHU SHASHANK", section: "B" },
  { rollNo: "25BD1A052B", name: "C SAI VIKAS REDDY", section: "B" },
  { rollNo: "25BD1A052C", name: "CHALLA LAXMI BHARGAVI", section: "B" },
  { rollNo: "25BD1A052D", name: "CHAMALA AKSHAYA BHARATHI", section: "B" },
  { rollNo: "25BD1A052E", name: "CHINCHOLE GANESH", section: "B" },
  { rollNo: "25BD1A052F", name: "CHUKKA NIKSHITH GOUD", section: "B" },
  { rollNo: "25BD1A052G", name: "DASARI SHIVA PRASAD", section: "B" },
  { rollNo: "25BD1A052H", name: "DHARAVATH MEGHANA", section: "B" },
  { rollNo: "25BD1A052J", name: "DODDI NAVEENA", section: "B" },
  { rollNo: "25BD1A052K", name: "DUDDU PRANAV", section: "B" },
  { rollNo: "25BD1A052L", name: "GADEELA RISHIKA", section: "B" },
  { rollNo: "25BD1A052M", name: "GADIPALLY RAMCHARAN", section: "B" },
  { rollNo: "25BD1A052N", name: "GORLI BALAADITYA", section: "B" },
  { rollNo: "25BD1A052P", name: "HEERAKAR VINAYAK LAL", section: "B" },
  { rollNo: "25BD1A052Q", name: "KAIROJU HEMA", section: "B" },
  { rollNo: "25BD1A052R", name: "KATKURI SAI AVINASH", section: "B" },
  { rollNo: "25BD1A052T", name: "KATNAM SHIVA", section: "B" },
  { rollNo: "25BD1A052U", name: "KATRAPALLI ADITYA SAI", section: "B" },
  { rollNo: "25BD1A052V", name: "KORIVI SAI CHANDRA", section: "B" },
  { rollNo: "25BD1A052W", name: "KURRA HARSHITHA", section: "B" },
  { rollNo: "25BD1A052X", name: "MALLEVAINA SHIVA SAKETH", section: "B" },
  { rollNo: "25BD1A052Y", name: "MANDA RAMCHARAN", section: "B" },
  { rollNo: "25BD1A052Z", name: "MANUPATI PAVAN", section: "B" },
  { rollNo: "25BD1A0531", name: "MARTHI JISHNU BALAJI", section: "B" },
  { rollNo: "25BD1A0532", name: "MULAKALAPALLI REVANTH MANI TEJ", section: "B" },
  { rollNo: "25BD1A0533", name: "NANDALA DIKSHITH", section: "B" },
  { rollNo: "25BD1A0534", name: "NIRNAKAR ANIRUDH", section: "B" },
