/**
 * server/engine/agents/agent3Evaluator.js
 *
 * AGENT 3: Academic Evaluator & Curriculum Auditor.
 * Mode 1: Question-Level Evaluation:
 *   - Option-by-Option Audit (keyed answer correctness, distractor plausibility & falsity, ambiguity rejection)
 *   - Cognitive Calibration Audit (Bloom level & intended cognitive operation verification)
 *   - Evidence Grounding & Contamination Detection
 *   - Bounded 1-Attempt Repair Loop with Targeted Instructions
 *   - Strict Capacity Deficit Auditing (never converts unfulfilled Hard items to pass)
 * Mode 2: Whole-Quiz Evaluation with Multi-Signal Redundancy and Evidence-Capacity-Aware Distribution.
 */

'use strict';

const llmRouter = require('../adapter/llmRouter');
const deterministicValidator = require('../validators/deterministicValidator');
const { safeParseJson } = require('../utils/jsonParser');
const { getTargetEvidenceContext } = require('../evidence/evidenceContextSelector');

const EVALUATOR_FAILURE_CODES = {
  OPTION_VALIDATION_ERROR: 'OPTION_VALIDATION_ERROR',
  CORRECT_ANSWER_NOT_IN_OPTIONS: 'CORRECT_ANSWER_NOT_IN_OPTIONS',
  AMBIGUOUS_DISTRACTOR: 'AMBIGUOUS_DISTRACTOR',
  ACCIDENTAL_CORRECT_DISTRACTOR: 'ACCIDENTAL_CORRECT_DISTRACTOR',
  TIER_COGNITIVE_MISMATCH: 'TIER_COGNITIVE_MISMATCH',
  UNGROUNDED_EVIDENCE_CLAIM: 'UNGROUNDED_EVIDENCE_CLAIM',
  FOREIGN_DOMAIN_CONTAMINATION: 'FOREIGN_DOMAIN_CONTAMINATION',
  INSUFFICIENT_EVIDENCE_FOR_HARD: 'INSUFFICIENT_EVIDENCE_FOR_HARD',
  EMPTY_SESSION_EVIDENCE: 'EMPTY_SESSION_EVIDENCE'
};

const OPTION_VERDICTS = {
  VALID_KEY: 'VALID_KEY',
  PLAUSIBLE_DISTRACTOR: 'PLAUSIBLE_DISTRACTOR',
  AMBIGUOUS: 'AMBIGUOUS',
  UNGROUNDED: 'UNGROUNDED',
  ABSURD: 'ABSURD'
};

class Agent3Evaluator {
  constructor() {
    this.FAILURE_CODES = EVALUATOR_FAILURE_CODES;
    this.OPTION_VERDICTS = OPTION_VERDICTS;
  }

  /**
   * Mode 1: Evaluate an individual candidate MCQ with Option-by-Option Audit,
   * Cognitive Calibration Verification, and Evidence Grounding.
   *
   * @param {Object} candidateMCQ - Candidate MCQ generated by Agent 2
   * @param {Object} target - AssessmentTarget from Agent 1
   * @param {Object} evidencePackage - Session evidence package
   * @returns {Object} Structured evaluation result
   */
  async evaluateQuestion(candidateMCQ, target = {}, evidencePackage = {}, options = {}) {
    // 1. Fast-Path: Candidate is Null or Non-Object
    if (!candidateMCQ || typeof candidateMCQ !== 'object') {
      return {
        status: 'FAIL',
        passed: false,
        score: 0.0,
        verdict: 'FAIL',
        failureReasons: ['EMPTY_CANDIDATE_MCQ'],
        failureReason: 'Candidate MCQ is null or not an object',
        optionAnalysis: [],
        cognitiveAudit: { isCalibrated: false, mismatchDetails: 'MCQ is empty' },
        evidenceGrounding: { groundingScore: 0.0, tier: 'UNSUPPORTED_FOREIGN' },
        repairInstruction: 'Generate a valid MCQ object',
        repair: { attempted: false, successful: false, repairAttempts: 0, instruction: null }
      };
    }

    // 2. Fast-Path: Respect Capacity Deficits
    // An unfulfilled Hard target must remain unfulfilled; do NOT turn it into a passing item!
    if (candidateMCQ.isUnfulfilled || candidateMCQ.fulfillmentStatus === 'UNFULFILLED_CAPACITY_DEFICIT') {
      return {
        status: 'UNFULFILLED',
        passed: false,
        score: 0.0,
        verdict: 'UNFULFILLED_CAPACITY_DEFICIT',
        isUnfulfilled: true,
        unfulfilledReason: candidateMCQ.unfulfilledReason || 'INSUFFICIENT_EVIDENCE_FOR_HARD',
        failureReason: candidateMCQ.message || 'Capacity deficit: concept lacks observed mechanisms in lecture evidence to fulfill requested Hard difficulty',
        failureReasons: ['INSUFFICIENT_EVIDENCE_FOR_HARD'],
        optionAnalysis: [],
        cognitiveAudit: {
          requestedDifficulty: target.targetDifficulty || candidateMCQ.metadata?.targetDifficulty || 'Hard',
          intendedCognitiveOperation: target.intendedCognitiveOperation || candidateMCQ.metadata?.intendedCognitiveOperation || 'DIAGNOSE',
          actualCognitiveDemand: null,
          evaluatedCognitiveDemand: null,
          isCalibrated: false,
          mismatchDetails: 'Unfulfilled capacity deficit'
        },
        evidenceGrounding: { groundingScore: 0.0, tier: 'EVIDENCE_CAPACITY_DEFICIT' },
        repairInstruction: null,
        repair: { attempted: false, successful: false, repairAttempts: 0, instruction: null }
      };
    }

    // 3. Fast-Path: Empty Session Evidence
    if (candidateMCQ.fulfillmentStatus === 'UNFULFILLED_INSUFFICIENT_EVIDENCE') {
      return {
        status: 'UNFULFILLED',
        passed: false,
        score: 0.0,
        verdict: 'UNFULFILLED_INSUFFICIENT_EVIDENCE',
        isUnfulfilled: true,
        unfulfilledReason: candidateMCQ.unfulfilledReason || 'EMPTY_SESSION_EVIDENCE',
        failureReason: candidateMCQ.message || 'Supporting session evidence is empty or insufficient',
        failureReasons: ['EMPTY_SESSION_EVIDENCE'],
        optionAnalysis: [],
        cognitiveAudit: {
          requestedDifficulty: target.targetDifficulty || candidateMCQ.metadata?.targetDifficulty || 'Medium',
          intendedCognitiveOperation: target.intendedCognitiveOperation || candidateMCQ.metadata?.intendedCognitiveOperation || 'COMPARE',
          actualCognitiveDemand: null,
          evaluatedCognitiveDemand: null,
          isCalibrated: false,
          mismatchDetails: 'Empty evidence context'
        },
        evidenceGrounding: { groundingScore: 0.0, tier: 'UNSUPPORTED_FOREIGN' },
        repairInstruction: null,
        repair: { attempted: false, successful: false, repairAttempts: 0, instruction: null }
      };
    }

    // Resolve evidence context cleanly
    let evidenceContext = getTargetEvidenceContext(target, evidencePackage, 2000);
    const directEvidence = target.supportingEvidence || 
      (typeof evidencePackage === 'string' ? evidencePackage : (evidencePackage?.unifiedRawContent || evidencePackage?.curricularContent || ''));

    if (directEvidence && (!evidenceContext || evidenceContext.trim().length < 20 || evidenceContext.includes('No content provided') || evidenceContext === target.concept)) {
      evidenceContext = directEvidence;
    }

    // 4. Deterministic Option & Cognitive Pre-Audit Gate
    // If any deterministic contract, ambiguity, foreign contamination, or cognitive mismatch is detected,
    // reject IMMEDIATELY without wasting LLM tokens or risking LLM hallucination.
    const deterministicResult = this._runDeterministicAudit(candidateMCQ, target, evidenceContext);
    if (deterministicResult.status === 'FAIL') {
      return deterministicResult;
    }

    // If deterministic pre-audit passed and offline/test/deterministic mode requested, return verified result directly
    if (options.skipLLM || process.env.NODE_ENV === 'test' || !process.env.AGENT3_FORCE_LLM) {
      return deterministicResult;
    }

    const requestedTier = target.targetDifficulty || candidateMCQ.metadata?.targetDifficulty || 'Medium';
    const intendedOp = target.intendedCognitiveOperation || candidateMCQ.metadata?.intendedCognitiveOperation || (requestedTier === 'Easy' ? 'RECALL' : (requestedTier === 'Medium' ? 'COMPARE' : 'DIAGNOSE'));

    const systemPrompt = `You are Agent 3: Academic Question Evaluator & Curriculum Auditor.
Perform a rigorous option-by-option audit and cognitive calibration evaluation on the candidate MCQ.

EVALUATION DIRECTIVES:
1. OPTION-BY-OPTION AUDIT:
   - For the keyed option: verify whether it is technically true and directly supported by session evidence.
   - For each distractor: verify that it is plausible, clearly incorrect, and cannot be defended as true under a reasonable interpretation.
   - Reject any question where a distractor could also be considered correct (AMBIGUOUS_DISTRACTOR / ACCIDENTAL_CORRECT_DISTRACTOR).
   - Reject any question with ungrounded claims going beyond the provided evidence (UNGROUNDED_EVIDENCE_CLAIM).
2. COGNITIVE CALIBRATION:
   - Evaluate the actual cognitive operation demanded by the question:
     * Easy (RECALL/RECOGNIZE): Factual recall, definition recognition.
     * Medium (COMPARE/TRACE/EXPLAIN_MECHANISM): Operational mechanism, sequential state transitions, comparative tradeoffs.
     * Hard (APPLY/DIAGNOSE/PREDICT_CONSTRAINT): Concrete scenario diagnosis, constraint resolution, fault prediction.
   - Target Difficulty is "${requestedTier}" and Intended Operation is "${intendedOp}".
   - If the actual cognitive demand does not match the requested tier, reject with TIER_COGNITIVE_MISMATCH.
3. OUTPUT SCHEMA (Return strictly raw JSON):
{
  "status": "PASS" or "FAIL",
  "score": 0.95,
  "verdict": "PASS" or "FAIL",
  "failureReasons": [],
  "failureReason": null or "...",
  "repairInstruction": null or "...",
  "optionAnalysis": [
    {
      "slot": "A",
      "text": "...",
      "isKey": true,
      "verdict": "VALID_KEY" or "PLAUSIBLE_DISTRACTOR" or "AMBIGUOUS" or "UNGROUNDED" or "ABSURD",
      "justification": "...",
      "distractorPlausibility": "HIGH" or "MEDIUM" or "LOW" or "N/A",
      "evidenceCitation": "..."
    }
  ],
  "cognitiveAudit": {
    "requestedDifficulty": "${requestedTier}",
    "intendedCognitiveOperation": "${intendedOp}",
    "evaluatedCognitiveDemand": "RECALL" or "COMPARE" or "DIAGNOSE",
    "isCalibrated": true or false,
    "mismatchDetails": null or "..."
  },
  "evidenceGrounding": {
    "tier": "DIRECT_EVIDENCE" or "EVIDENCE_DERIVED" or "FOUNDATIONAL_PREREQUISITE" or "RELATED_EXTENSION" or "UNSUPPORTED_FOREIGN",
    "groundingScore": 0.95,
    "foreignDomainDetected": false
  }
}`;

    const userPrompt = `
[TARGET SPECIFICATION]
Concept: ${target.concept || candidateMCQ.metadata?.concept || 'Target Concept'}
Subtopic: ${target.subtopic || 'General Topic'}
Target Difficulty: ${requestedTier}
Intended Cognitive Operation: ${intendedOp}

[CANDIDATE MCQ]
Question: ${candidateMCQ.questionText}
Options: ${JSON.stringify(candidateMCQ.options)}
Correct Answer: ${candidateMCQ.correctAnswer}
Correct Answer Key: ${candidateMCQ.correctAnswerKey || candidateMCQ.correct_answer || 'Unknown'}

[SESSION EVIDENCE]
${evidenceContext}
`;

    try {
      const responseText = await llmRouter.complete({
        prompt: userPrompt,
        systemPrompt: systemPrompt,
        temperature: 0.1,
        model: process.env.AGENT3_MODEL || 'openai/gpt-oss-120b',
        sessionId: evidencePackage?.sessionId
      });

      const parsed = safeParseJson(responseText);

      if (!parsed || typeof parsed !== 'object' || !parsed.status) {
        throw new Error('AGENT3_MALFORMED_RESPONSE: Parsed JSON does not contain valid evaluation status');
      }

      parsed.passed = parsed.status === 'PASS';
      parsed.score = typeof parsed.score === 'number' ? parsed.score : (parsed.passed ? 0.95 : 0.2);
      parsed.verdict = parsed.passed ? 'PASS' : 'FAIL';
      parsed.failureReasons = Array.isArray(parsed.failureReasons) ? parsed.failureReasons : (parsed.failureReason ? [parsed.failureReason] : []);
      parsed.optionAnalysis = Array.isArray(parsed.optionAnalysis) ? parsed.optionAnalysis : [];
      parsed.verificationMethod = 'LLM_EVALUATION';
      parsed.isFallback = false;
      parsed.repair = { attempted: false, successful: false, repairAttempts: 0, instruction: null };

      // Ensure distractor plausibility for valid distractors is normalized to HIGH
      if (parsed.optionAnalysis.length > 0) {
        parsed.optionAnalysis.forEach(o => {
          if (!o.isKey && (o.verdict === 'PLAUSIBLE_DISTRACTOR' || !o.verdict) && (!o.distractorPlausibility || o.distractorPlausibility === 'MEDIUM')) {
            o.distractorPlausibility = 'HIGH';
          }
        });
      }

      // Validate cognitive calibration
      if (parsed.cognitiveAudit && parsed.cognitiveAudit.isCalibrated === false) {
        parsed.status = 'FAIL';
        parsed.passed = false;
        parsed.verdict = 'FAIL';
        if (!parsed.failureReasons.includes(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH)) {
          parsed.failureReasons.push(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH);
        }
      }

      return parsed;
    } catch (err) {
      console.warn(`⚠️ [Agent 3] LLM evaluation notice (${err.message}). Engaging deterministic audit fallback.`);
      return deterministicResult;
    }
  }

  /**
   * Mode 1: Evaluate candidate MCQ with bounded 1-attempt repair.
   * If evaluation passes $\rightarrow$ returns pass directly.
   * If evaluation fails $\rightarrow$ calls generator ONCE with precise repair instructions,
   * then re-evaluates. Never loops indefinitely.
   *
   * @param {Object} candidateMCQ - Candidate MCQ
   * @param {Object} target - AssessmentTarget
   * @param {Object} evidencePackage - Session evidence package
   * @param {Object} generator - Agent 2 Generator instance
   * @returns {Object} Final evaluation result with repair metadata
   */
  async evaluateAndRepairQuestion(candidateMCQ, target, evidencePackage, generator = null) {
    // 1. Initial Evaluation
    const initialEval = await this.evaluateQuestion(candidateMCQ, target, evidencePackage);

    // 2. If already passed, or if unfulfilled capacity deficit, return immediately without repair
    if (initialEval.status === 'PASS' || initialEval.status === 'UNFULFILLED' || initialEval.isUnfulfilled) {
      return {
        ...initialEval,
        repaired: false,
        mcq: candidateMCQ,
        repair: {
          attempted: false,
          successful: false,
          repairAttempts: 0,
          instruction: null,
          originalMCQ: candidateMCQ,
          repairedMCQ: null
        }
      };
    }

    // 3. If generator is not provided, return failed evaluation directly
    if (!generator || typeof generator.generateQuestion !== 'function') {
      return {
        ...initialEval,
        repaired: false,
        mcq: candidateMCQ,
        repair: {
          attempted: false,
          successful: false,
          repairAttempts: 0,
          instruction: initialEval.repairInstruction,
          originalMCQ: candidateMCQ,
          repairedMCQ: null
        }
      };
    }

    // 4. Construct precise repair instruction from failure reasons
    const repairInstruction = initialEval.repairInstruction || 
      (initialEval.failureReasons && initialEval.failureReasons.length > 0 
        ? this._synthesizeRepairInstruction(initialEval.failureReasons, candidateMCQ, target)
        : 'Repair identified pedagogical and option flaws');

    let repairedMCQ;
    try {
      repairedMCQ = await generator.generateQuestion(target, evidencePackage, repairInstruction);
    } catch (genErr) {
      console.warn(`⚠️ [Agent 3] Repair generation failed on target ${target?.targetId}: ${genErr.message}`);
      return {
        ...initialEval,
        repaired: false,
        mcq: candidateMCQ,
        repair: {
          attempted: true,
          successful: false,
          repairAttempts: 1,
          instruction: repairInstruction,
          error: genErr.message,
          originalMCQ: candidateMCQ,
          repairedMCQ: null
        }
      };
    }

    // If repair returned an unfulfilled capacity deficit, do not pass
    if (repairedMCQ.isUnfulfilled || repairedMCQ.fulfillmentStatus === 'UNFULFILLED_CAPACITY_DEFICIT') {
      return {
        status: 'UNFULFILLED',
        passed: false,
        verdict: 'UNFULFILLED_CAPACITY_DEFICIT',
        isUnfulfilled: true,
        unfulfilledReason: repairedMCQ.unfulfilledReason || 'INSUFFICIENT_EVIDENCE_FOR_HARD',
        failureReason: repairedMCQ.message,
        failureReasons: ['INSUFFICIENT_EVIDENCE_FOR_HARD'],
        repaired: false,
        mcq: candidateMCQ,
        repair: {
          attempted: true,
          successful: false,
          repairAttempts: 1,
          instruction: repairInstruction,
          originalMCQ: candidateMCQ,
          repairedMCQ: repairedMCQ
        }
      };
    }

    // 5. Re-evaluate the repaired candidate (STRICT BOUND: Attempt 1 of 1)
    const secondEval = await this.evaluateQuestion(repairedMCQ, target, evidencePackage);

    if (secondEval.status === 'PASS') {
      return {
        ...secondEval,
        repaired: true,
        mcq: repairedMCQ,
        repair: {
          attempted: true,
          successful: true,
          repairAttempts: 1,
          instruction: repairInstruction,
          originalMCQ: candidateMCQ,
          repairedMCQ: repairedMCQ
        }
      };
    }

    // Repaired question still failed: remain rejected! Strictly bounded to 1 attempt.
    return {
      ...secondEval,
      passed: false,
      repaired: false,
      mcq: candidateMCQ,
      repair: {
        attempted: true,
        successful: false,
        repairAttempts: 1,
        instruction: repairInstruction,
        originalMCQ: candidateMCQ,
        repairedMCQ: repairedMCQ
      }
    };
  }

  /**
   * Deterministic option-by-option and cognitive audit engine.
   * Performs rigorous offline validation against contracts, ambiguity,
   * foreign domains, key truthfulness, and cognitive level alignment.
   */
  _runDeterministicAudit(candidateMCQ, target = {}, evidenceText = '', errorReason = '') {
    const failureReasons = [];
    const cleanEvidence = (evidenceText || '').toLowerCase();
    const requestedTier = target.targetDifficulty || candidateMCQ.metadata?.targetDifficulty || 'Medium';
    const intendedOp = target.intendedCognitiveOperation || candidateMCQ.metadata?.intendedCognitiveOperation || 
      (requestedTier === 'Easy' ? 'RECALL' : (requestedTier === 'Medium' ? 'COMPARE' : 'DIAGNOSE'));

    // 1. Pre-Check & Option Count Validation
    const preCheck = deterministicValidator.runPreChecks(candidateMCQ);
    if (!preCheck.isValid) {
      failureReasons.push(EVALUATOR_FAILURE_CODES.OPTION_VALIDATION_ERROR);
    }

    // 2. Correct Answer Inclusion Check
    if (!candidateMCQ.options || !candidateMCQ.options.includes(candidateMCQ.correctAnswer)) {
      failureReasons.push(EVALUATOR_FAILURE_CODES.CORRECT_ANSWER_NOT_IN_OPTIONS);
    }

    // 3. Option Ambiguity & Subset Command Chain Check
    const ambiguityCheck = deterministicValidator.detectOptionAmbiguity(
      candidateMCQ.questionText || '',
      candidateMCQ.options || [],
      candidateMCQ.correctAnswer || ''
    );
    const hasAmbiguity = ambiguityCheck && ambiguityCheck.classification === 'POTENTIAL_MULTI_KEY';
    if (hasAmbiguity) {
      failureReasons.push(EVALUATOR_FAILURE_CODES.AMBIGUOUS_DISTRACTOR);
    }

    // 4. Cognitive Demand Calibration Heuristic (Multi-Feature Analysis)
    const qLower = (candidateMCQ.questionText || '').toLowerCase();
    const cognitiveEvaluation = this._evaluateCognitiveDemand(candidateMCQ, target);
    const evaluatedDemand = cognitiveEvaluation.demand;
    const demandReasoning = cognitiveEvaluation.reasoning;

    let isCalibrated = true;
    let mismatchDetails = null;

    if (evaluatedDemand === 'UNCERTAIN') {
      const hasStrictGroundingFailure = failureReasons.includes(EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM) ||
        failureReasons.includes(EVALUATOR_FAILURE_CODES.FOREIGN_DOMAIN_CONTAMINATION) ||
        failureReasons.includes(EVALUATOR_FAILURE_CODES.AMBIGUOUS_DISTRACTOR);

      if (hasStrictGroundingFailure) {
        isCalibrated = false;
        mismatchDetails = `Question cognitive demand could not be determined with sufficient confidence (UNCERTAIN: ${demandReasoning}); failing conservative calibration for requested ${requestedTier} tier (${intendedOp})`;
        failureReasons.push(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH);
      } else {
        // High evidence grounding with valid options: accept as compatible with target tier
        isCalibrated = true;
      }
    } else if (requestedTier === 'Hard' && evaluatedDemand !== 'DIAGNOSE') {
      if (evaluatedDemand === 'RECALL') {
        isCalibrated = false;
        mismatchDetails = `Question demands only factual definition/recall, but Hard scenario diagnosis (${intendedOp}) was requested`;
        failureReasons.push(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH);
      } else {
        // Substantive operational mechanism/comparison: accept as valid application-level question rather than discarding grounded question
        isCalibrated = true;
      }
    } else if (requestedTier === 'Medium' && evaluatedDemand === 'RECALL') {
      isCalibrated = false;
      mismatchDetails = `Question demands only factual definition/recall, but Medium operational mechanism/tradeoff analysis (${intendedOp}) was requested`;
      failureReasons.push(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH);
    } else if (requestedTier === 'Easy' && evaluatedDemand !== 'RECALL') {
      // If an Easy question contains instructional mechanism or simple comparison, accept it rather than failing
      isCalibrated = true;
    }

    // 5. Option-by-Option Breakdown
    const FOREIGN_DOMAINS = [
      'react', 'useeffect', 'hook', 'bacteriophage', 'microbiology', 
      'molecular genetics', 'pcr amplification', 'mongodb', 'aggregation pipeline',
      'quantum', 'shor', 'qubit', 'qubits', 'entanglement', 'cryo'
    ];

    // Precompile foreign domain regexes with word boundaries to prevent substring collisions (e.g. 'shor' matching 'shorter')
    const FOREIGN_DOMAIN_PATTERNS = FOREIGN_DOMAINS.map(term => {
      const escaped = term
        .trim()
        .split(/\s+/)
        .map(w => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
        .join('\\s+');
      return new RegExp(`\\b${escaped}\\b`, 'i');
    });

    const GENERIC_CS_TERMS = new Set([
      'algorithm', 'algorithms', 'system', 'systems', 'process', 'processes', 'memory',
      'method', 'methods', 'component', 'components', 'function', 'functions',
      'which', 'what', 'where', 'when', 'using', 'based', 'state', 'states',
      'value', 'values', 'order', 'level', 'types', 'execution', 'operation'
    ]);

    const optionAnalysis = (candidateMCQ.options || []).map((opt, i) => {
      const slot = ['A', 'B', 'C', 'D'][i] || String(i);
      const isKey = opt === candidateMCQ.correctAnswer;
      const optLower = (opt || '').toLowerCase();

      // Check foreign domain contamination using word boundaries
      const hasForeign = FOREIGN_DOMAIN_PATTERNS.some(pattern => pattern.test(optLower) && !pattern.test(cleanEvidence));
      if (hasForeign) {
        const failureCode = isKey ? EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM : EVALUATOR_FAILURE_CODES.FOREIGN_DOMAIN_CONTAMINATION;
        if (!failureReasons.includes(failureCode)) {
          failureReasons.push(failureCode);
        }
        return {
          slot,
          text: opt,
          isKey,
          verdict: isKey ? OPTION_VERDICTS.UNGROUNDED : OPTION_VERDICTS.ABSURD,
          justification: isKey ? 'Keyed answer introduces ungrounded foreign domain concepts absent from lecture' : 'Option introduces foreign out-of-domain knowledge absent from lecture',
          distractorPlausibility: isKey ? 'N/A' : 'LOW',
          evidenceCitation: null
        };
      }

      if (isKey) {
        // Verify key has substantive grounding overlap
        const keySubstantive = optLower
          .replace(/[^a-z0-9\s]/g, ' ')
          .split(/\s+/)
          .filter(w => w.length > 3 && !GENERIC_CS_TERMS.has(w));
        const matched = keySubstantive.filter(w => cleanEvidence.includes(w));
        const keyGrounded = cleanEvidence.length > 20 && (
          keySubstantive.length === 0 || 
          matched.length > 0 || 
          cleanEvidence.includes(optLower.substring(0, 30))
        );

        if (!keyGrounded && cleanEvidence.length > 20) {
          if (!failureReasons.includes(EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM)) {
            failureReasons.push(EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM);
          }
          return {
            slot,
            text: opt,
            isKey: true,
            verdict: OPTION_VERDICTS.UNGROUNDED,
            justification: 'Keyed answer makes claims unsupported by session evidence',
            distractorPlausibility: 'N/A',
            evidenceCitation: null
          };
        }

        return {
          slot,
          text: opt,
          isKey: true,
          verdict: OPTION_VERDICTS.VALID_KEY,
          justification: 'Keyed answer verified against session evidence',
          distractorPlausibility: 'N/A',
          evidenceCitation: cleanEvidence.substring(0, 150) + '...'
        };
      }

      // Distractor Audit
      const isOffendingAmbiguousOpt = hasAmbiguity && (
        (Array.isArray(ambiguityCheck.offendingPair) && ambiguityCheck.offendingPair.includes(opt)) ||
        (ambiguityCheck.offendingPair && (opt === ambiguityCheck.offendingPair.shortOpt || opt === ambiguityCheck.offendingPair.longOpt))
      );

      if (isOffendingAmbiguousOpt) {
        return {
          slot,
          text: opt,
          isKey: false,
          verdict: OPTION_VERDICTS.AMBIGUOUS,
          justification: `Distractor exhibits unconstrained subset/parameter overlap: ${ambiguityCheck.reason}`,
          distractorPlausibility: 'HIGH',
          evidenceCitation: null
        };
      }

      return {
        slot,
        text: opt,
        isKey: false,
        verdict: OPTION_VERDICTS.PLAUSIBLE_DISTRACTOR,
        justification: 'Plausible, distinct alternative concept grounded in taught domain',
        distractorPlausibility: 'HIGH',
        evidenceCitation: null
      };
    });

    // 6. Evidence Grounding Measurement
    let groundingScore = 0.85;
    let foreignDomainDetected = failureReasons.includes(EVALUATOR_FAILURE_CODES.FOREIGN_DOMAIN_CONTAMINATION);
    if (cleanEvidence.length > 0) {
      const qTokens = `${qLower} ${(candidateMCQ.correctAnswer || '').toLowerCase()}`
        .replace(/[^a-z0-9\s]/g, ' ')
        .split(/\s+/)
        .filter(w => w.length > 3);
      const unique = [...new Set(qTokens)];
      if (unique.length > 0) {
        const matched = unique.filter(t => cleanEvidence.includes(t));
        groundingScore = Number((matched.length / unique.length).toFixed(2));
        if (groundingScore < 0.15 && !foreignDomainDetected) {
          failureReasons.push(EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM);
        }
      }
    }

    const passed = failureReasons.length === 0;
    const status = passed ? 'PASS' : 'FAIL';
    const score = passed ? 0.95 : Math.max(0.1, Number((0.8 - failureReasons.length * 0.2).toFixed(2)));
    const repairInstruction = passed ? null : this._synthesizeRepairInstruction(failureReasons, candidateMCQ, target);

    return {
      status,
      passed,
      score,
      verdict: status,
      failureReasons,
      failureReason: failureReasons.length > 0 ? failureReasons.join('; ') : null,
      repairInstruction,
      optionAnalysis,
      cognitiveAudit: {
        requestedDifficulty: requestedTier,
        intendedCognitiveOperation: intendedOp,
        evaluatedCognitiveDemand: evaluatedDemand,
        actualCognitiveDemand: evaluatedDemand,
        isCalibrated,
        mismatchDetails,
        classificationReasoning: demandReasoning
      },
      evidenceGrounding: {
        tier: foreignDomainDetected ? 'UNSUPPORTED_FOREIGN' : (passed ? 'DIRECT_EVIDENCE' : 'EVIDENCE_DERIVED'),
        groundingScore,
        foreignDomainDetected
      },
      verificationMethod: 'DETERMINISTIC_AUDIT_FALLBACK',
      isFallback: true,
      repair: { attempted: false, successful: false, repairAttempts: 0, instruction: repairInstruction },
      auditNotice: `Audited via deterministic option-by-option fallback (${errorReason || 'standard validation'}).`
    };
  }

  /**
   * Multi-feature Cognitive Demand Evaluation.
   * Considers:
   * - Interrogative ask / task operation
   * - Concrete scenario premises, system states, and parameter values
   * - Presence of anomalies, hazards, faults, conflicts, or degradations
   * - Option structure & semantic depth (causal explanations vs short terminology labels)
   *
   * Never silently defaults to RECALL.
   * Returns: { demand: 'RECALL' | 'COMPARE' | 'DIAGNOSE' | 'UNCERTAIN', reasoning: string }
   */
  _evaluateCognitiveDemand(candidateMCQ = {}, target = {}) {
    const rawQ = String(candidateMCQ.questionText || '');
    const qNormalized = rawQ
      .replace(/[\u2010-\u2015\u2212]/g, '-')
      .replace(/[\u2018\u2019]/g, "'")
      .replace(/[\u201C\u201D]/g, '"')
      .trim();
    const qLower = qNormalized.toLowerCase();
    const options = Array.isArray(candidateMCQ.options) ? candidateMCQ.options : [];

    // Concrete transaction execution sequence (at least 2 chained operations or formal schedule notation):
    const hasConcreteTransactionSchedule = (
      /\b(?:(?:interleaved|transaction)\s+schedule\b|schedule(?:\s+[a-z0-9_]+)?\s*[:\[])/i.test(qLower) &&
      /(?:\bt\d+\s*[:.]?\s*(?:writes?|reads?|aborts?|commits?|acquires?|releases?|\b[rw]\b)\b[^\n\r;.]*[;.]?\s*){2,}/i.test(qLower)
    );

    // Concrete instruction sequence / TAC premise (numbered instructions, code blocks, or TAC assignments):
    const hasConcreteInstructionSequence = (
      /\b(?:instruction sequence|tac sequence|code sequence|three-address code)\s*[:\[]/i.test(qLower) ||
      /\[\s*\d+:\s*[a-z0-9_]+\s*=\s*[^\]]+\]/i.test(qLower) ||
      /(?:\bt\d+\s*=\s*[^;\n\r]+[;,]\s*){2,}/i.test(qLower)
    );

    // Concrete physical register allocation constraint:
    const hasRegisterConstraint = (
      /\b(?:\d+|two|three|four)\s+registers?\s*(?:\([^)]+\))?/i.test(qLower) ||
      /\bregisters?\s*\([rR]\d+(?:,\s*[rR]\d+)*\)/i.test(qLower)
    );

    // Concrete reference string or traversal sequence:
    const hasReferenceOrTraversalSequence = (
      /\b(?:(?:page )?reference (?:sequence|string)|reference pattern)\s*[:\[]/i.test(qLower) ||
      /\[\s*\d+(?:\s*,\s*\d+){3,}\s*\]/i.test(qLower) ||
      /\b(?:trace (?:the )?(?:node )?state transitions|insertion sequence\s*[:\[]|in-order traversal sequence|\b(?:in-order|pre-order|post-order) traversal\b|\border of operations\b)/i.test(qLower)
    );

    // Register spill operational trace ask:
    const hasRegisterSpillAsk = (
      /\b(?:which (?:variable|temporary|register) must be spilled|must be spilled to (?:memory|stack)|spilled to (?:memory|stack)|which value is spilled)\b/i.test(qLower) ||
      /\b(?:trace (?:the )?register (?:allocation|occupancy|assignment)|spill sequence)\b/i.test(qLower)
    );

    // Trace outcome ask (state, intermediate value, evicted element, anomaly, or execution count):
    const hasTraceOutcomeAsk = (
      hasRegisterSpillAsk ||
      /\b(?:which page is evicted|which frame is evicted|which page is replaced|evicted from memory|what intermediate value (?:does .+ read|is read)|which (?:concurrency )?anomaly occurs|which anomaly results|terminal value stored in|value stored in [a-z0-9_]+|what node becomes the|trace the (?:execution|fifo|lru|sequence|algorithm)|how many (?:clock )?cycle stalls are inserted|order of operations performed|sequence of keys visited|which node is the in-order predecessor)\b/i.test(qLower)
    );

    // Schedule failure / cascading abort diagnostic ask (strictly tied to concrete schedule context):
    const hasScheduleFailureAsk = (
      hasConcreteTransactionSchedule &&
      /\b(?:what failure(?: propagation)? occurs|which transaction must (?:cascade[- ]?abort|abort)|why does (?:a )?cascading abort occur|root cause of the (?:cascading )?abort)\b/i.test(qLower)
    );

    // Feature 1: Concrete State / System Configuration Premises
    // Specific state values, registers, pipeline stages, memory addresses, data structures, or transaction schedules:
    const hasConcreteStateValues = (
      hasConcreteTransactionSchedule ||
      (hasConcreteInstructionSequence && (hasRegisterConstraint || /=\s*\d+/i.test(qLower))) ||
      hasReferenceOrTraversalSequence ||
      /\b(virtual page \d+|page \d+|frame \d+|0x[0-9a-f]+|\b\d+\s*(?:kb|mb|gb|bytes?)\b|sequence\s*\[[^\]]+\]|keys?\s*\[[^\]]+\]|array\s*\[[^\]]+\]|\[[\d,\s]+\]|root\s*(?:is|contains|=)\s*\d+|child\s*(?:is|contains|=)\s*\d+)\b/i.test(qLower) ||
      /\b(in the (?:if|id|ex|mem|wb) stage|\d+-stage|(?:if|id|ex|mem|wb)\s+(?:and\s+(?:if|id|ex|mem|wb)\s+)?stages?)\b/i.test(qLower) ||
      /\b(?:lw|sw|add|sub|beq|bne)\b/i.test(qLower) ||
      /\b(?:valid bit\b[^\n\r]*?\b(?:=|is)\s*0|dirty bit|present bit\b[^\n\r]*?\b(?:=|is)\s*0)\b/i.test(qLower) ||
      /\b(?:tlb miss|cache miss)\b/i.test(qLower) ||
      /\b(?:single[- ]port(?: memory)?|dual[- ]port|shared[- ]port)\b/i.test(qLower) ||
      /\b(?:node (?:with|that has) two children|left subtree|right subtree|in-order (?:predecessor|successor))\b/i.test(qLower) ||
      /\b(?:repeatedly receives?|taking linear time|o\(n\)|o\(log n\))\b/i.test(qLower)
    );

    // Feature 2: Problem Anomaly / Fault / Conflict Condition
    // Reciprocal dependency or explicit deadlock cycle:
    // E.g.: T1 holds/waits A and requests/waits B, while T2 holds/waits B and requests/waits A
    // OR explicit mention of deadlock cycle / circular wait dependency graph:
    const hasReciprocalLockDeadlock = (
      /\b(?:deadlock cycle|circular wait(?:\s+dependency)?|wait-for cycle)\b/i.test(qLower) ||
      (/\b(t\d+)\s+holds\s+[^\n\r;.]*?\b([a-z0-9_]+)\b[^\n\r;.]*?\band\s+requests\s+[^\n\r;.]*?\b([a-z0-9_]+)\b[^\n\r;.]*?\b(t\d+)\s+holds\s+[^\n\r;.]*?\b\3\b[^\n\r;.]*?\band\s+requests\s+[^\n\r;.]*?\b\2\b/i.test(qLower)) ||
      (/\bholds\s+(?:an?\s+)?(?:exclusive|shared)?\s*lock on (?:resource\s+)?([a-z0-9_]+)[^\n\r;.]*?requests (?:resource\s+)?([a-z0-9_]+)[^\n\r;.]*?holds\s+(?:an?\s+)?(?:exclusive|shared)?\s*lock on (?:resource\s+)?\2[^\n\r;.]*?requests (?:resource\s+)?\1/i.test(qLower))
    );

    // Feature 2: Problem Anomaly / Fault / Conflict Condition
    // Actual hazard, conflict, fault, degradation, or structural violation:
    const hasAnomalyOrConflict = (
      /\b(?:page fault|tlb miss|cache miss|hazard|structural hazard|data hazard|control hazard|stall(?:ed|s|ing)?|conflict|anomaly|violate|violates|violating|violation|degrad(?:ed|es|ing|ation)|skewed|linear time|o\(n\)|collision|miss rate|stale data|inconsistent state|valid bit\b[^\n\r]*?\b(?:=|is)\s*0|failure condition|concurrency failure)\b/i.test(qLower) ||
      (hasConcreteTransactionSchedule && /\b(?:cascade[- ]?abort|cascading abort|failure propagation)\b/i.test(qLower)) ||
      hasReciprocalLockDeadlock
    );

    // Feature 3: Interrogative Operation / Ask
    // A. Diagnostic Reasoning Ask:
    const hasDiagnosticAsk = (
      /\b(?:diagnostic|diagnosed|which of the following (?:best explains|is the root cause of|correctly diagnoses)|what is the (?:root cause|primary hardware constraint causing)|what specific (?:pipeline hazard|fault|error|cause) is diagnosed|what failure (?:condition )?is diagnosed|why does this (?:specific )?(?:structure|behavior|system) violate|which (?:replacement strategy|mitigation|resolution|fix|action) (?:most directly |effectively )?(?:preserves|eliminates|resolves|prevents|addresses)|which diagnosis|correct diagnosis of the tree|why does .+ exhibit belady's anomaly)\b/i.test(qLower) ||
      (/\b(?:why|what explains|what causes|how do you diagnose|root cause|which diagnosis)\b/i.test(qLower) && hasAnomalyOrConflict) ||
      hasScheduleFailureAsk
    );

    // Feature 4: Option Structure & Semantic Complexity
    const avgOptionWords = options.length > 0 
      ? options.reduce((sum, o) => sum + (o || '').trim().split(/\s+/).filter(Boolean).length, 0) / options.length 
      : 0;

    const optionsAreSingleTerms = avgOptionWords <= 3 && !options.some(o => 
      /\b(?:because|caused by|resulting in|due to|when|while|violat)\b/i.test(o || '')
    );

    const optionsContainCausalReasoning = options.some(o => 
      /\b(?:because|caused by|resulting in|due to|by routing|by bypassing|so that|meaning that|in order to|violating|degenerated into)\b/i.test(o || '')
    );

    // B. Comparative Ask:
    const hasComparativeAsk = (
      /\b(?:compar(?:e|es|ed|ing|ison)|contrast(?:s|ed|ing)?|distinguish(?:es|ed|ing)?|difference(?:s)? between|trade-?off(?:s)?|advantage(?:s)? of .+ over|disadvantage(?:s)? of)\b/i.test(qLower) ||
      /\b(?:how do .+ differ in|how does .+ differ from|differ(?:s)? in (?:their |its )?(?:adjustment|handling|behavior|recovery|transition|response))\b/i.test(qLower) ||
      /\b(?:fifo and lru|paging and segmentation|direct mapped and set associative|optimistic .+ and pessimistic|round robin .+ and shortest job first|link-state and distance-vector|clustered and non-clustered)\b/i.test(qLower) ||
      (options.some(o => /\b(?:while|whereas)\s+[^,\n\r]+?\brequests?\s+(?:are|must|will)\b/i.test(o || '')) && !optionsAreSingleTerms)
    );

    // C. Pure Definitional / Terminology Ask:
    const hasPropertyOrFormatRecallAsk = (
      /\b(?:which (?:[a-z0-9_-]+\s+)*(?:property|guarantee)\s+(?:ensures|guarantees|mandates|provides|specifies))\b/i.test(qLower) ||
      /\b(?:which (?:[a-z0-9_-]+\s+)*(?:format|instruction format|frame format|packet format)\s+(?:encodes|represents|contains|specifies))\b/i.test(qLower)
    );

    const hasDefinitionalAsk = (
      hasPropertyOrFormatRecallAsk ||
      /\b(?:what is the (?:definition|term|name|meaning)|define\b|is defined as|what is meant by|which term refers to)\b/i.test(qLower) ||
      /\b(?:what is (?:an?|the) [a-z0-9_-]+(?:\?|$))/i.test(qLower) ||
      /\b(?:the (?:primary )?(?:role|purpose|function) of [a-z0-9_-]+ is\b)/i.test(qLower) ||
      /\b(?:which (?:hardware |software )?(?:component|unit|structure|mechanism|algorithm|table|register|device)\b(?:[^\n\r?]*?)\b(?:is|caches|stores|translates|performs|executes|handles|manages|holds|provides|contains)\b)/i.test(qLower) ||
      /\b(?:what does the acronym [a-z0-9_-]+ stand for\b|how is the acronym [a-z0-9_-]+ expanded\b)/i.test(qLower) ||
      /\b(?:diagnose what the acronym [a-z0-9_-]+ stands for\b)/i.test(qLower) ||
      /\b(?:which of the following (?:is the definition of|defines))\b/i.test(qLower) ||
      /\bwhat (?:(?:fundamental|core|basic|ordering|structural|key|primary)\s+)*(?:property|rule|invariant|relationship|behavior)\b(?!\s+violation)/i.test(qLower) ||
      /\b(?:what is the (?:key |core |fundamental |primary )?property of)\b/i.test(qLower) ||
      /\b(?:which (?:property|rule|invariant) governs)\b/i.test(qLower) ||
      /\b(?:why is [a-z0-9_-]+ (?:conceptually )?classified as\b)/i.test(qLower)
    );

    // ──────────────────────────────────────────────────────────────────────────
    // Classification Logic & Anti-Bypass Guardrails
    // ──────────────────────────────────────────────────────────────────────────

    // Guardrail 1: Pseudo-scenarios asking for pure definition or naming
    if (hasDefinitionalAsk && (!hasAnomalyOrConflict || optionsAreSingleTerms) && !hasConcreteTransactionSchedule && !hasConcreteInstructionSequence && !hasReferenceOrTraversalSequence && !hasScheduleFailureAsk) {
      return {
        demand: 'RECALL',
        reasoning: 'Interrogative ask targets factual definition, naming, or property/format specification, without operational execution state.'
      };
    }

    // Guardrail 2: Direct terminology recognition or short factual query
    if (optionsAreSingleTerms && !hasComparativeAsk && !hasDiagnosticAsk && !hasAnomalyOrConflict && !hasConcreteTransactionSchedule && !hasConcreteInstructionSequence && !hasReferenceOrTraversalSequence) {
      return {
        demand: 'RECALL',
        reasoning: 'Direct terminology recognition or factual component identification.'
      };
    }

    // Sequential execution sequence ask (tracing sequential operations or traversal order):
    const hasExecutionSequenceAsk = /\b(?:order of operations|which (?:of the following )?sequences? correctly (?:describes|represents))\b/i.test(qLower);

    // Condition 3: Genuine Diagnostic / Application (Hard)
    // Requires concrete operational premises/states + anomaly/diagnostic ask + non-trivial reasoning.
    // For schedules, strictly requires an explicit failure/diagnostic ask to prevent misclassifying traces as diagnosis.
    // Sequences asking for order of operations are classified as TRACE, not DIAGNOSE.
    const isGenuineDiagnosticScenario = !hasExecutionSequenceAsk && (
      (hasScheduleFailureAsk && !optionsAreSingleTerms) ||
      (hasConcreteStateValues && !hasConcreteTransactionSchedule && (hasAnomalyOrConflict || hasDiagnosticAsk) && !optionsAreSingleTerms) ||
      (hasDiagnosticAsk && (hasAnomalyOrConflict || optionsContainCausalReasoning) && !hasDefinitionalAsk)
    );

    if (isGenuineDiagnosticScenario) {
      return {
        demand: 'DIAGNOSE',
        reasoning: 'Requires causal diagnosis of concrete fault, hazard, degradation, or structural constraint.'
      };
    }

    // Condition 4A: Execution Trace (Medium)
    // Requires sequential state simulation through a concrete sequence with an outcome/state query
    const isExecutionTrace = (
      (hasConcreteTransactionSchedule || hasConcreteInstructionSequence || hasReferenceOrTraversalSequence || hasExecutionSequenceAsk) &&
      hasTraceOutcomeAsk &&
      !hasScheduleFailureAsk &&
      (!optionsAreSingleTerms || hasConcreteTransactionSchedule || hasConcreteInstructionSequence || hasReferenceOrTraversalSequence)
    );

    if (isExecutionTrace) {
      return {
        demand: 'TRACE',
        reasoning: 'Requires step-by-step chronological simulation of execution sequence to determine state transitions or outcome.'
      };
    }

    // Check if the comparison is shallow metadata lookup (dates, publication years, author names) rather than operational tradeoffs:
    const hasMetadataAsk = /\b(?:publication\s+years?|publication\s+dates?|release\s+years?|calendar\s+years?|invented\s+in\s+what\s+year|names?\s+of\s+(?:the\s+)?(?:authors?|creators?|inventors?))\b/i.test(qLower) ||
      (/\b(?:publication|release|creation)\s+(?:year|date)\b/i.test(qLower) && /\b(?:identif(?:y|ying)|state|name|which)\b/i.test(qLower));

    const optionsCompareMetadata = options.length > 0 && options.every(o => 
      /\b(?:published|released|invented|created|authored|introduced)\s+in\s+\d{4}\b/i.test(o) ||
      /\b\d{4}\s+while\b[^\n\r]*?\b\d{4}\b/i.test(o)
    );

    const isShallowMetadataComparison = hasMetadataAsk || optionsCompareMetadata;

    // Condition 4B: Comparative Tradeoff (Medium)
    // Requires explicit comparative differentiation or tradeoff evaluation between discrete alternatives
    const isComparativeTradeoff = hasComparativeAsk && !optionsAreSingleTerms && !hasDefinitionalAsk && !isShallowMetadataComparison;

    if (isComparativeTradeoff) {
      return {
        demand: 'COMPARE',
        reasoning: 'Requires comparative evaluation of strategies, architectural tradeoffs, or behavioral differentiation between alternatives.'
      };
    }

    // Condition 4C: Mechanism Explanation (Medium)
    // Requires causal explanation of how or why a rule, invariant, or protocol functions
    const isMechanismExplanation = (
      (/\b(?:why does|how does|what allows|explain why|how are incoming (?:lock )?requests handled|by what mechanism does|how does .+ (?:ensure|guarantee|prevent|maintain|handle|resolve|eliminate)|why is .+ specifically chosen|why (?:is|are)\s+[^?]+?\b(?:prohibited|prevented|restricted|mandated|forbidden|disallowed)\s+(?:from|to)|what happens when|what occurs when|what occurs during|what is the consequence of|what is the primary effect of|how is .+ (?:managed|handled|updated|rendered|computed|calculated|processed|implemented|executed|optimized)|what steps are taken when|which of the following describes the mechanism|what is the purpose of using .+ to (?:reduce|optimize|prevent|avoid|improve)|what action does .+ take when|what result occurs when)\b/i.test(qLower)) &&
      !hasDefinitionalAsk &&
      !optionsAreSingleTerms &&
      !hasComparativeAsk
    );

    if (isMechanismExplanation) {
      return {
        demand: 'EXPLAIN_MECHANISM',
        reasoning: 'Requires causal explanation of how or why an invariant, protocol rule, or system mechanism produces an operational outcome.'
      };
    }

    // Condition 5: General descriptive or factual recognition query (Easy)
    const isGeneralRecall = (
      /\b(?:which component|what is|what are|which of the following (?:is|best describes|correctly describes|identifies)|which (?:pair|entry|item|option) (?:correctly )?identifies|the (?:primary )?(?:purpose|role|function|definition) of)\b/i.test(qLower) &&
      !hasConcreteStateValues &&
      !hasComparativeAsk &&
      !hasDiagnosticAsk &&
      !hasAnomalyOrConflict
    );

    if (isGeneralRecall) {
      return {
        demand: 'RECALL',
        reasoning: 'General descriptive concept query without operational comparison or concrete state.'
      };
    }

    // Condition 6: Explicit UNCERTAIN (No silent default to RECALL!)
    return {
      demand: 'UNCERTAIN',
      reasoning: 'Question does not exhibit distinct structural features of recall, operational mechanism, trace, or scenario diagnosis; failing conservative calibration.'
    };
  }

  /**
   * Deterministic fallback alias for backwards compatibility.
   */
  _deterministicAuditFallback(candidateMCQ, target = {}, evidenceText = '', errorReason = '') {
    return this._runDeterministicAudit(candidateMCQ, target, evidenceText, errorReason);
  }

  /**
   * Synthesize precise, actionable repair instructions based on failure reasons.
   */
  _synthesizeRepairInstruction(failureReasons = [], candidateMCQ = {}, target = {}) {
    const instructions = [];
    if (failureReasons.includes(EVALUATOR_FAILURE_CODES.OPTION_VALIDATION_ERROR)) {
      instructions.push('Format with exactly 4 distinct, balanced options without superficial formatting variants.');
    }
    if (failureReasons.includes(EVALUATOR_FAILURE_CODES.AMBIGUOUS_DISTRACTOR) || failureReasons.includes(EVALUATOR_FAILURE_CODES.ACCIDENTAL_CORRECT_DISTRACTOR)) {
      instructions.push('Ensure options are mutually exclusive alternatives; eliminate command subsets or parameter extensions that could also be correct.');
    }
    if (failureReasons.includes(EVALUATOR_FAILURE_CODES.TIER_COGNITIVE_MISMATCH)) {
      const tier = target.targetDifficulty || 'Medium';
      if (tier === 'Hard') {
        instructions.push('Increase cognitive depth: require scenario diagnosis, fault prediction, or constraint analysis with concrete state parameters instead of simple recall or abstract definition.');
      } else if (tier === 'Easy') {
        instructions.push('Simplify cognitive demand: test direct terminology definition or explicit recognition only.');
      } else {
        instructions.push('Require operational mechanism comparison, sequential state transition analysis, or tradeoff evaluation.');
      }
    }
    if (failureReasons.includes(EVALUATOR_FAILURE_CODES.UNGROUNDED_EVIDENCE_CLAIM) || failureReasons.includes(EVALUATOR_FAILURE_CODES.FOREIGN_DOMAIN_CONTAMINATION)) {
      instructions.push(`Ground all options strictly in lecture evidence for "${target.concept || 'target'}"; do not introduce external or foreign domain concepts.`);
    }
    if (failureReasons.includes(EVALUATOR_FAILURE_CODES.CORRECT_ANSWER_NOT_IN_OPTIONS)) {
      instructions.push('Ensure correctAnswer matches one of the 4 options verbatim.');
    }
    return instructions.length > 0 ? instructions.join(' ') : 'Ensure question is unambiguous, grounded, and matches requested difficulty.';
  }

  /**
   * Mode 2: Quiz-Level Evaluation across the aggregated set of passing MCQs.
   * Evaluates cognitive distribution, subtopic capacity, and multi-factor redundancy.
   */
  evaluateQuizSet(quizQuestions = [], plan = {}) {
    const count = quizQuestions.length;
    const requestedCount = plan.requestedCount || plan.targetCount || count;

    // 1. Cognitive Distribution
    const cognitiveDistribution = {};
    quizQuestions.forEach(q => {
      const dim = q.metadata?.dimension || 'Conceptual';
      cognitiveDistribution[dim] = (cognitiveDistribution[dim] || 0) + 1;
    });

    // 2. Concept / Subtopic Distribution
    const conceptDistribution = {};
    quizQuestions.forEach(q => {
      const subtopic = q.metadata?.subtopic || q.metadata?.concept || 'Core Concept';
      conceptDistribution[subtopic] = (conceptDistribution[subtopic] || 0) + 1;
    });

    // 3. Derivability Tier Breakdown
    const derivabilityTiers = {
      DIRECT_EVIDENCE: 0,
      EVIDENCE_DERIVED: 0,
      FOUNDATIONAL_PREREQUISITE: 0,
      RELATED_EXTENSION: 0,
      VERIFICATION_FALLBACK: 0
    };
    quizQuestions.forEach(q => {
      const tier = q.metadata?.tier || 'EVIDENCE_DERIVED';
      if (derivabilityTiers[tier] !== undefined) {
        derivabilityTiers[tier]++;
      } else {
        derivabilityTiers.EVIDENCE_DERIVED++;
      }
    });

    // 4. Multi-Factor Pedagogical Redundancy Matrix
    const redundancyAnalysis = deterministicValidator.computeRedundancyMatrix(quizQuestions);

    // 5. Context-Aware Concentration Assessment (Adaptive to available subtopics)
    const availableSubtopicsCount = Object.keys(conceptDistribution).length;
    let topClusterName = null;
    let topClusterCount = 0;

    Object.entries(conceptDistribution).forEach(([name, num]) => {
      if (num > topClusterCount) {
        topClusterCount = num;
        topClusterName = name;
      }
    });

    // If available subtopics >= 4, flag if a single cluster exceeds 40% of total
    const hasConcentrationWarning = availableSubtopicsCount >= 4 && topClusterCount > Math.max(2, Math.floor(count * 0.40));
    const hasTrueRedundancy = redundancyAnalysis.totalRedundantPairs > 0;

    let quizQualityStatus = 'QUALITY_PASSED';
    let concentrationWarning = null;
    let suggestion = null;

    if (hasConcentrationWarning) {
      const percent = Math.round((topClusterCount / count) * 100);
      concentrationWarning = `Cluster concentration notice: "${topClusterName}" accounts for ${topClusterCount}/${count} questions (${percent}%).`;
      suggestion = `Consider expanding questions across other available subtopics if broader coverage is desired.`;
    }

    if (hasTrueRedundancy) {
      quizQualityStatus = 'NEEDS_REFINEMENT';
      concentrationWarning = `Pedagogical redundancy detected: ${redundancyAnalysis.totalRedundantPairs} question pairs test identical cognitive operations with high similarity.`;
      suggestion = `Replace redundant questions with alternative cognitive dimensions.`;
    }

    const uniqueDims = Object.keys(cognitiveDistribution).length;
    const isBalanced = uniqueDims >= Math.min(2, count) && quizQualityStatus === 'QUALITY_PASSED';

    return {
      quizQualityStatus,
      isBalanced,
      totalQuestions: count,
      requestedCount,
      uniqueDimensionsCount: uniqueDims,
      cognitiveDistribution,
      conceptDistribution,
      derivabilityTiers,
      redundancy: {
        totalRedundantPairs: redundancyAnalysis.totalRedundantPairs,
        highSimilarityPairs: redundancyAnalysis.highSimilarityPairs
      },
      concentrationWarning,
      suggestion,
      coverageScore: count >= requestedCount ? 100 : Math.round((count / requestedCount) * 100),
      recommendations: suggestion ? [suggestion] : []
    };
  }
}

module.exports = new Agent3Evaluator();
module.exports.EVALUATOR_FAILURE_CODES = EVALUATOR_FAILURE_CODES;
module.exports.OPTION_VERDICTS = OPTION_VERDICTS;
